# the name of your track or event
name = "Decentralized Job Fair @ IPFS Camp"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Jeremy Kloth"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://lu.ma/ipfscamp22.jobfair"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "17:00 - 19:00"

# the event venue name (will show up on the event card - TODO)
venueName = "[Convento do Beato](https://goo.gl/maps/2yDdwVSHfgs1mYhL7)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Alameda do Beato 40, 1950-042 Lisboa, Portugal"

# the max number of attendees of the event
attendees = ""


# these is unsued:
# tickets = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Workshops","Networking"]

# a color, to group key events visually. use sparingly
color="green"

# A small logomark for the corner of the event
logomark = "/logomarks/Protocol Labs.jpeg"

# a description of the event.
# will show up when the user clicks the event card.
description = """
Helping the network grow one builder and founder at a time.  Come join our decentralized job fair that will showcase those in our network who are building some amazing products in the web3 space. 
"""

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
# priority = 
