# the name of your track or event
name = "libp2p Day"

# the name of the group organizing the event
org = "libp2p Team"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Prithvi Shahi"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://discuss.libp2p.io/t/first-ever-libp2p-day-oct-30-lisbon-portugal/1582"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "10:00 - 21:00"

# the event venue name (will show up on the event card - TODO)
venueName = "[Convento do Beato](https://goo.gl/maps/2yDdwVSHfgs1mYhL7)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Alameda do Beato 40, 1950-042 Lisboa, Portugal"

# the max number of attendees of the event
attendees = ""


# these is unsued:
# tickets = ""

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
color="green"

# A small logomark for the corner of the event
logomark = "/logomarks/libp2p.png"

# a description of the event.
# will show up when the user clicks the event card.
description = """
libp2p day will be a part of IPFS Camp 2022. libp2p day is going to be a gathering for the whole libp2p community: builders, contributors, and maintainers. Join us as we present what we’ve all been working on, and where we want to go. We’ll have talks aimed at turning devs into libp2p builders, builders into contributors, and contributors into spec authors. We’ll also have time for discussion groups and hacking. All within the greater context of IPFS Camp 2022.
"""
